$(document).ready(function(){
	$("#ne").click(function(){
		$("#n").toggle();
		$("#1").toggle();
	});
	$("#one").click(function(){
		$("#o").toggle();
		$("#2").toggle();
	});
	$("#two").click(function(){
		$("#t").toggle();
		$("#3").toggle();
	});
	$("#three").click(function(){
		$("#th").toggle();
		$("#4").toggle();
	});
	$("#four").click(function(){
		$("#fo").toggle();
		$("#5").toggle();
	});
	
});